[project]
name = "mapit"
version = "0.1.0"
description = ""
authors = [
    {name = "Jesper Thøgersen",email = "s203841@dtu.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry]
packages = [{include = "mapit", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
lint.select = ["E", "F", "I", "B", "D"]  # E: pycodestyle, F: pyflakes, I: isort, B: flake8-bugbear, D: pydocstyle rules
lint.ignore = ["E501", "D100", "D104"]
target-version = "py310"